# Generated by Django 4.1.7 on 2023-04-23 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assign_service',
            fields=[
                ('assign_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_request_id', models.IntegerField()),
                ('employee_login_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('service_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_assign_service',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_category',
            },
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=50)),
                ('reply', models.CharField(default='Nil', max_length=50)),
                ('user_login_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_complaint',
            },
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('email_id', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('photo', models.CharField(max_length=50)),
                ('desingnation', models.CharField(max_length=50)),
                ('login_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_employee',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=50)),
                ('reply', models.CharField(default='Nil', max_length=50)),
                ('employee_login_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_feedback',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.TextField(null=True)),
                ('Usertype', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_login',
            },
        ),
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('Cocunselor_name', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'tbl_meeting',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_login_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_order',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('features', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
        migrations.CreateModel(
            name='service_request',
            fields=[
                ('service_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_service', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('vehicle_brand', models.CharField(max_length=50)),
                ('vehicle_no', models.CharField(max_length=50)),
                ('date_of_completion', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('user_login_id', models.IntegerField()),
                ('entry_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'tbl_service',
            },
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('sub_category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_sub_category',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.IntegerField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('Email', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('place', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]
