# Generated by Django 4.1.7 on 2023-04-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0002_district_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='workshop',
            fields=[
                ('workshop_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.IntegerField()),
                ('Name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('ownername', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('district_id', models.IntegerField()),
                ('place', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_workshop',
            },
        ),
    ]
