# Generated by Django 4.1.7 on 2023-04-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0003_workshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='area',
        ),
    ]
