# Generated by Django 4.1.7 on 2023-04-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0004_remove_workshop_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='workshop_login_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
