# Generated by Django 4.1.7 on 2023-04-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0005_employee_workshop_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='workshop_login_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
